ke = {
        'url_login' : 'http://automationpractice.com/index.php?controller=authentication',
        'url_afterlogin' : 'http://automationpractice.com/index.php?controller=my-account',
        'url_new_user' : 'http://automationpractice.com/index.php?controller=authentication#account-creation',
        'email' : '875060@cognizant.com',
        'passwd' : 'abcde',
        'invalid_email' : '87506@cognizant.com',
        'invalid_passwd' : 'abcd',
        'email_create' : '6789@gmail.com',
        'first_name' : 'him',
        'last_name' : 'kas',
        'password' : 'abcde',
        'dob_day' : '10',
        'dob_month' : '2',
        'dob_year' : '15',
        'address_first_name' : 'him',
        'address_last_name' : 'kas',
        'address_companyname' : 'Book',
        'address_address1' : 'calle general pardinas 44',
        'address_address2' : 'apt 7a',
        'address_city' : 'Los Angeles',
        'address_state' : '6',
        'address_zip' : '28001',
        'address_country' : '2',
        'address_additional_info' : 'test info',
        'address_home_phone' : '619722287',
        'address_mobile_phone' : '620722287',
        'address_alias' : '',
        'search1_top' : 'Printed Chiffon Dress',
        'search2_top' : 'Printed Summer Dress',
        'payment_type' : 'Pay by bank wire'
}

